//common
export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const REGISTER_API = "REGISTER_API";
export const REGISTER_API_SUCCEED = "REGISTER_API_SUCCEED";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const FORGOTPASSWORD_API = "FORGOTPASSWORD_API";
export const FORGOTPASSWORD_API_SUCCEED = "FORGOTPASSWORD_API_SUCCEED";
export const FORGOTPASSWORD_API_FAIL = "FORGOTPASSWORD_API_FAIL";

export const RESETPASSWORD_API = "RESETPASSWORD_API";
export const RESETPASSWORD_API_SUCCEED = "RESETPASSWORD_API_SUCCEED";
export const RESETPASSWORD_API_FAIL = "RESETPASSWORD_API_FAIL";
//admin
export const GET_USER = "GET_USER";
export const GET_USER_SUCCEED = "GET_USER_SUCCEED";
export const GET_USER_FAILED = "GET_USER_FAILED";