//common
export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const REGISTER_API = "REGISTER_API";
export const REGISTER_API_SUCCEED = "REGISTER_API_SUCCEED";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const FORGOTPASSWORD_API = "FORGOTPASSWORD_API";
export const FORGOTPASSWORD_API_SUCCEED = "FORGOTPASSWORD_API_SUCCEED";
export const FORGOTPASSWORD_API_FAIL = "FORGOTPASSWORD_API_FAIL";

export const RESETPASSWORD_API = "RESETPASSWORD_API";
export const RESETPASSWORD_API_SUCCEED = "RESETPASSWORD_API_SUCCEED";
export const RESETPASSWORD_API_FAIL = "RESETPASSWORD_API_FAIL";

export const CHANGEPASSWORD_API = "CHANGEPASSWORD_API";
export const CHANGEPASSWORD_API_SUCCEED = "CHANGEPASSWORD_API_SUCCEED";
export const CHANGEPASSWORD_API_FAIL = "CHANGEPASSWORD_API_FAIL";
//admin
export const SET_TITLE = "SET_TITLE";
export const SET_SHOW_SIDE_BAR = "SET_SHOW_SIDE_BAR";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCEED = "GET_USER_SUCCEED";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const GET_MANAGER = "GET_MANAGER";
export const GET_MANAGER_SUCCEED = "GET_MANAGER_SUCCEED";
export const GET_MANAGER_FAILED = "GET_MANAGER_FAILED";

export const DELETE_USER = "GET_DELETE_USER";
export const DELETE_USER_SUCCEED = "GET_DELETE_USER_SUCCEED";
export const DELETE_USER_FAILED = "GET_DELETE_USER_FAILED";

export const GET_ALL_ACCOUNT_WAITING = "GET_ALL_ACCOUNT_WAITING";
export const GET_ALL_ACCOUNT_WAITING_SUCCEED =
  "GET_ALL_ACCOUNT_WAITING_SUCCEED";
export const GET_ALL_ACCOUNT_WAITING_FAILED = "GET_ALL_ACCOUNT_WAITING_FAILED";

export const ACCEPT_USER_REGISTER = "ACCEPT_USER_REGISTER";
export const ACCEPT_USER_REGISTER_SUCCEED = "ACCEPT_USER_REGISTER_SUCCEED";
export const ACCEPT_USER_REGISTER_FAILED = "ACCEPT_USER_REGISTER_FAILED";

export const DENY_USER_REGISTER = "DENY_USER_REGISTER";
export const DENY_USER_REGISTER_SUCCEED = "DENY_USER_REGISTER_SUCCEED";
export const DENY_USER_REGISTER_FAILED = "DENY_USER_REGISTER_FAILED";

export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";
export const GET_ALL_DEPARTMENTS_SUCCEED = "GET_ALL_DEPARTMENTS_SUCCEED";
export const GET_ALL_DEPARTMENTS_FAILED = "GET_ALL_DEPARTMENTS_FAILED";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_ACCOUNT_SUCCEED = "UPDATE_ACCOUNT_SUCCEED";
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNT_FAILED";

export const ADD_MANAGER = "ADD_MANAGER";
export const ADD_MANAGER_SUCCEED = "ADD_MANAGER_SUCCEED";
export const ADD_MANAGER_FAILED = "ADD_MANAGER_FAILED";

export const GET_PROJECTS_BY_USER_ID = "GET_PROJECTS_BY_USER_ID";
export const GET_PROJECTS_BY_USER_ID_SUCCEED =
  "GET_PROJECTS_BY_USER_ID_SUCCEED";
export const GET_PROJECTS_BY_USER_ID_FAILED = "GET_PROJECTS_BY_USER_ID_FAILED";

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const GET_ALL_PROJECT_SUCCEED = "GET_ALL_PROJECT_SUCCEED";
export const GET_ALL_PROJECT_FAILED = "GET_ALL_PROJECT_FAILED";

export const GET_ALL_PROJECT_BY_LEADER = "GET_ALL_PROJECT_BY_LEADER";
export const GET_ALL_PROJECT_BY_LEADER_SUCCEED =
  "GET_ALL_PROJECT_BY_LEADER_SUCCEED";
export const GET_ALL_PROJECT_BY_LEADER_FAILED =
  "GET_ALL_PROJECT_BY_LEADER_FAILED";

export const GET_ALL_USER_ASSIGNEE_BY_PROJECT_ID =
  "GET_ALL_USER_ASSIGNEE_BY_PROJECT_ID";
export const GET_ALL_USER_ASSIGNEE_BY_PROJECT_ID_SUCCEED =
  "GET_ALL_USER_ASSIGNEE_BY_PROJECT_ID_SUCCEED";
export const GET_ALL_USER_ASSIGNEE_BY_PROJECT_ID_FAILED =
  "GET_ALL_USER_ASSIGNEE_BY_PROJECT_ID_FAILED";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_SUCCEED = "CREATE_PROJECT_SUCCEED";
export const CREATE_PROJECT_FAILED = "CREATE_PROJECT_FAILED";

export const ASSIGN_USERS_INTO_PROJECT = "ASSIGN_USERS_INTO_PROJECT";
export const ASSIGN_USERS_INTO_PROJECT_SUCCEED =
  "ASSIGN_USERS_INTO_PROJECT_SUCCEED";
export const ASSIGN_USERS_INTO_PROJECT_FAILED =
  "ASSIGN_USERS_INTO_PROJECT_FAILED";

export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_SUCCEED = "UPDATE_PROJECT_SUCCEED";
export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_SUCCEED = "DELETE_PROJECT_SUCCEED";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";

// MANAGE TASK OF PROJECT
export const GET_ALL_TASKS_BY_PROJECT_ID = "GET_ALL_TASKS_BY_PROJECT_ID";
export const GET_ALL_TASKS_BY_PROJECT_ID_SUCCEED =
  "GET_ALL_TASKS_BY_PROJECT_ID_SUCCEED";
export const GET_ALL_TASKS_BY_PROJECT_ID_FAILED =
  "GET_ALL_TASKS_BY_PROJECT_ID_FAILED";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCEED = "CREATE_TASK_SUCCEED";
export const CREATE_TASK_FAILED = "CREATE_TASK_FAILED";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCEED = "UPDATE_TASK_SUCCEED";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCEED = "DELETE_TASK_SUCCEED";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED";

// MANAGE SCHEDULE
export const ADD_LEAVE_REQUEST = "ADD_LEAVE_REQUEST";
export const ADD_LEAVE_REQUEST_SUCCEED = "ADD_LEAVE_REQUEST_SUCCEED";
export const ADD_LEAVE_REQUEST_FAILED = "ADD_LEAVE_REQUEST_FAILED";

export const GET_SCHEDULE_BY_USER_ID = "GET_SCHEDULE_BY_USER_ID";
export const GET_SCHEDULE_BY_USER_ID_SUCCEED =
  "GET_SCHEDULE_BY_USER_ID_SUCCEED";
export const GET_SCHEDULE_BY_USER_ID_FAILED = "GET_SCHEDULE_BY_USER_ID_FAILED";

export const GET_ALL_SCHEDULES = "GET_ALL_SCHEDULES";
export const GET_ALL_SCHEDULES_SUCCEED = "GET_ALL_SCHEDULES_SUCCEED";
export const GET_ALL_SCHEDULES_FAILED = "GET_ALL_SCHEDULES_FAILED";

export const UPDATE_SCHEDULE_BY_ID = "UPDATE_SCHEDULE_BY_ID";
export const UPDATE_SCHEDULE_BY_ID_SUCCEED = "UPDATE_SCHEDULE_BY_ID_SUCCEED";
export const UPDATE_SCHEDULE_BY_ID_FAILED = "UPDATE_SCHEDULE_BY_ID_FAILED";

export const DELETE_SCHEDULE_BY_ID = "DELETE_SCHEDULE_BY_ID";
export const DELETE_SCHEDULE_BY_ID_SUCCEED = "DELETE_SCHEDULE_BY_ID_SUCCEED";
export const DELETE_SCHEDULE_BY_ID_FAILED = "DELETE_SCHEDULE_BY_ID_FAILED";

//MANAGE FEEDBACK BY TASK ID

export const GET_ALL_FEEDBACKS_BY_TASK_ID = "GET_ALL_FEEDBACKS_BY_TASK_ID";
export const GET_ALL_FEEDBACKS_BY_TASK_ID_SUCCEED =
  "GET_ALL_FEEDBACKS_BY_TASK_ID_SUCCEED";
export const GET_ALL_FEEDBACKS_BY_TASK_ID_FAILED =
  "GET_ALL_FEEDBACKS_BY_TASK_ID_FAILED";

export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK";
export const UPDATE_FEEDBACK_SUCCEED = "UPDATE_FEEDBACK_SUCCEED";
export const UPDATE_FEEDBACK_FAILED = "UPDATE_FEEDBACK_FAILED";

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const ADD_FEEDBACK_SUCCEED = "ADD_FEEDBACK_SUCCEED";
export const ADD_FEEDBACK_FAILED = "ADD_FEEDBACK_FAILED";

export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const DELETE_FEEDBACK_SUCCEED = "DELETE_FEEDBACK_SUCCEED";
export const DELETE_FEEDBACK_FAILED = "DELETE_FEEDBACK_FAILED";

//MANAGE PERMISSION LEADER

export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const GET_ALL_PERMISSIONS_SUCCEED = "GET_ALL_PERMISSIONS_SUCCEED";
export const GET_ALL_PERMISSIONS_FAILED = "GET_ALL_PERMISSIONS_FAILED";

export const GET_PERMISSIONS_BY_LEADER_ID = "GET_PERMISSIONS_BY_LEADER_ID";
export const GET_PERMISSIONS_BY_LEADER_ID_SUCCEED =
  "GET_PERMISSIONS_BY_LEADER_ID_SUCCEED";
export const GET_PERMISSIONS_BY_LEADER_ID_FAILED =
  "GET_PERMISSIONS_BY_LEADER_ID_FAILED";

export const UPDATE_PERMISSION_LEADER_ID = "UPDATE_PERMISSION_LEADER_ID";
export const UPDATE_PERMISSION_LEADER_ID_SUCCEED =
  "UPDATE_PERMISSION_LEADER_ID_SUCCEED";
export const UPDATE_PERMISSION_LEADER_ID_FAILED =
  "UPDATE_PERMISSION_LEADER_ID_FAILED";

//intern
export const GET_PROFILE_INTERN = "GET_PROFILE_INTERN";
export const GET_PROFILE_INTERN_SUCCEED = "GET_PROFILE_INTERN_SUCCEED";
export const GET_PROFILE_INTERN_FAILED = "GET_PROFILE_INTERN_FAILED";

export const GET_LIST_FEEDBACK = "GET_LIST_FEEDBACK";
export const GET_LIST_FEEDBACK_SUCCEED = "GET_LIST_FEEDBACK_SUCCEED";
export const GET_LIST_FEEDBACK_FAILED = "GET_LIST_FEEDBACK_FAILED";

export const GET_DETAIL_FEEDBACK = "GET_DETAIL_FEEDBACK";
export const GET_DETAIL_FEEDBACK_SUCCEED = "GET_DETAIL_FEEDBACK_SUCCEED";
export const GET_DETAIL_FEEDBACK_FAILED = "GET_DETAIL_FEEDBACK_FAILED";

export const GET_PROJECT_INTERN = "GET_PROJECT_INTERN";
export const GET_PROJECT_INTERN_SUCCEED = "GET_PROJECT_INTERN_SUCCEED";
export const GET_PROJECT_INTERN_FAILED = "GET_PROJECT_INTERN_FAILED";

export const GET_TASK_PROJECT_INTERN = "GET_TASK_PROJECT_INTERN";
export const GET_TASK_PROJECT_INTERN_SUCCEED =
  "GET_TASK_PROJECT_INTERN_SUCCEED";
export const GET_TASK_PROJECT_INTERN_FAILED = "GET_TASK_PROJECT_INTERN_FAILED";

export const CHANGE_STATUS_TASK_INTERN = "CHANGE_STATUS_TASK_INTERN";
export const CHANGE_STATUS_TASK_INTERN_SUCCEED =
  "CHANGE_STATUS_TASK_INTERN_SUCCEED";
export const CHANGE_STATUS_TASK_INTERN_FAILED =
  "CHANGE_STATUS_TASK_INTERN_FAILED";

export const POST_LEAVE_SCHEDULE_INTERN = "POST_LEAVE_SCHEDULE_INTERN";
export const POST_LEAVE_SCHEDULE_INTERN_SUCCEED =
  "POST_LEAVE_SCHEDULE_INTERN_SUCCEED";
export const POST_LEAVE_SCHEDULE_INTERN_FAILED =
  "POST_LEAVE_SCHEDULE_INTERN_FAILED";
